AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  App:
    Type: String
    Default: "awsmonitoringv3"
  MyIp:
    Type: String
    Description: "Allow access to dashboards from my computer."


Resources:
  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref App
      EngineVersion: 'OpenSearch_1.3'
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: '1'
        ZoneAwarenessEnabled: false
        InstanceType: 't3.medium.search'
      EBSOptions:
        EBSEnabled: true
        Iops: '0'
        VolumeSize: '100'
        VolumeType: 'gp2'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
        override_main_response_version: true
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: 'arn:aws:iam::103050589342:user/dev'
            Action:
              - 'es:*'
            Resource:
              - !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${App}/*"
          - Effect: 'Allow'
            Principal:
              AWS: '*'
            Action:
              - 'es:*'
            Resource:
              - !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${App}/*"
            Condition:
              IpAddress:
                aws:SourceIp:
                - !Ref MyIp


Outputs:
  OpenSearchEndpoint:
    Description: OpenSearchEndpoint
    Value: !Sub "${OpenSearchServiceDomain.DomainEndpoint}"
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-OpenSearchEndpoint'